services:
  server:
    environment:
      NODE_ENV: production
      CORS_ORIGIN: ""
      FRONTEND_URL: ""
    volumes: []

  frontend:
    build:
      target: prod
      args:
        VITE_API_URL: ""
    ports:
      - "80:80"
    environment:
      VITE_API_URL: ""
    volumes: []
